language: java
sudo: true
install:
jdk:
  - oraclejdk8
os:
  - linux
branches:
  only:
  - master
before_install:
 - chmod +x gradlew
script: "bash ./gradlew clean build --stacktrace"
notifications:

